name: tempo
description: Application Flutter "Tempo" - Agenda connecté, contacts et articles liés
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Database
  drift: ^2.14.1
  drift_sqflite: ^2.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Navigation
  go_router: ^12.1.3
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Network & Images
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  
  # Utilities
  intl: ^0.18.1
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Drift code generation
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Launcher icons
  flutter_launcher_icons: ^0.13.1
  
  # Image picker
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  
  # Preferences
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true

# Configuration for flutter_launcher_icons - Windows only
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "lib/features/assets/Tempo.png"
    icon_size: 48 # min:48, max:256, default: 48
